import Head from 'next/head'
import LayoutBase from "../../layout/base";
import { authPage } from '../../middlewares/authorizationPage'
import authorization from '../../middlewares/authorization'

export async function getServerSideProps(ctx) {
  try {
    const { token } = await authPage(ctx);
    const decode = await authorization(token);
    if (decode) {
      return {
        props: {
          dataToken: decode,
        },
      };
    } else {
      return ctx.res
        .writeHead(302, {
          Location: "/",
        })
        .end();
    }
  } catch (error) {
    return ctx.res
      .writeHead(302, {
        Location: "/",
      })
      .end();
  }
}

export default function Home(dataToken) {
  return (
    <LayoutBase dataToken={dataToken}>
      <Head>
        <title>Ipsos Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Row className='home'>
        <Col className='home_body'> */}
        <div className='home home_body'>
          <h1>SISTEM MONITORING PROJECT MANAGEMENT</h1>
          <img src="/images/building.png" alt="image home" width="100%"/>
        </div>
        {/* </Col>
      </Row> */}
    </LayoutBase>
  );
}
